const hyakuninisshu = [
  // {
  //   id: 6,
  //   kami: ["かささぎのわたせる", "橋におく霜の"],
  //   simo: ["白きをみれば", "夜ぞ更けにける"],
  //   karutaimg01: "/cyuunagonyakamochi_image01.svg",
  //   karutaimg02: "/cyuunagonyakamochi_image02.svg",
  //   fudekami: "/cyuunagonyakamochi_kami.png",
  //   fudesimo: "/cyuunagonyakamochi_simo.png",
  //   author: "中納言　家持",
  //   authoren: "cyuunagonyakamochi",
  // },
  // {
  //   id: 33,
  //   kami: ["久", "かたの", "ひかりのど", "けき", "春の", "日に"],
  //   simo: ["しづごころなくはなのちるらむ"],
  //   author: "紀　友則",
  //   authoren: "kinotomonori",
  // },
  {
    id: 1,
    kami: ["秋の田の", "仮庵の庵の", "苫をあらみ"],
    simo: ["わが衣手は 露にぬれつつ"],
    author: "天智天皇",
    authoren: "tenchitennou",
  },
  {
    id: 2,
    kami: ["春過ぎて", "夏来にけらし", "白妙の"],
    simo: ["衣ほすてふ", "天の香具山"],
    author: "持統天皇",
    authoren: "zitoutennou",
  },
  {
    id: 3,
    kami: ["あしひきの", "山どりの尾の", "しだり尾の"],
    simo: ["ながながし夜を", "ひとりかもねむ"],
    author: "柿本人麻呂",
    authoren: "kakinomotonohitomaro",
  },
  {
    id: 4,
    kami: ["田子の浦に", "うちいでて見れば", "白妙の"],
    simo: [" 富士の高嶺に", "雪はふりつつ"],
    author: "山部赤人",
    authoren: "yamabenoakahito",
  },
  {
    id: 5,
    kami: ["かささぎの", "わたせる橋に", "おく霜の"],
    simo: ["白きを見れば", "夜ぞふけにける"],
    author: "中納言家持",
    authoren: "cyuunagonyakamochi",
  },
  {
    id: 6,
    kami: ["天の原", "ふりさけ見れば", "春日なる"],
    simo: ["三笠の山に", "出でし月かも"],
    author: "安倍仲麿",
    authoren: "abenonakamaro",
  },
  {
    id: 7,
    kami: ["我が庵は", "都のたつみ", "しかぞすむ"],
    simo: ["世を宇治山と", "人はいふなり"],
    author: "喜撰法師",
    authoren: "kisenhoushi",
  },
  {
    id: 8,
    kami: ["花の色は", "うつりにけりな", "いたづらに"],
    simo: ["わが身世にふる", "ながめせしまに"],
    author: "小野小町",
    authoren: "ononokotmachi",
  },
  {
    id: 9,
    kami: ["これやこの", "行くも帰るも", "別れては"],
    simo: ["知るも知らぬも", "逢坂の関"],
    author: "蝉丸",
    authoren: "semimaru",
  },
  {
    id: 10,
    kami: ["わたの原", "八十島かけて", "漕ぎ出でぬと"],
    simo: ["人にはつげよ", "あまのつり舟"],
    author: "参議篁",
    authoren: "sanginotakamura",
  },
];

export default hyakuninisshu;
